# 02 Preprocessing

Week 3 objective: turn the CRMLS sold data into a cleaned dataset and prepare the time-based split plan for California single-family home close price prediction.

This notebook continues from `01_exploration.ipynb` and implements:

- missing value decisions: drop, convert invalid values to missing, or flag
- basic categorical and boolean cleaning
- row-level data quality fixes
- time-based train/test split setup using the most recent month as test
- preprocessing pipeline template for imputation, encoding, and scaling
- cleaned CSV export

## 0. Setup

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

CLEANED_CSV = PROCESSED_DATA_DIR / "crmls_week3_cleaned.csv"
SPLIT_PLAN_CSV = PROCESSED_DATA_DIR / "crmls_week3_split_plan.csv"

print(f"Project root: {PROJECT_ROOT}")
print(f"Raw data dir: {RAW_DATA_DIR}")
print(f"Cleaned CSV: {CLEANED_CSV}")
print(f"Split plan CSV: {SPLIT_PLAN_CSV}")

Project root: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction
Raw data dir: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/raw
Cleaned CSV: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/processed/crmls_week3_cleaned.csv
Split plan CSV: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/processed/crmls_week3_split_plan.csv

## 1. Load Raw Data

Each file is loaded with a `source_file` column so records remain traceable after combining monthly data.

In [2]:
def load_crmls_file(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, low_memory=False)
    df["source_file"] = path.name
    return df

csv_files = sorted(RAW_DATA_DIR.glob("CRMLSSold*.csv"))

raw_df = pd.concat([load_crmls_file(path) for path in csv_files], ignore_index=True)

print(f"Loaded files: {len(csv_files)}")
print([path.name for path in csv_files])
print(f"Raw shape: {raw_df.shape}")

Loaded files: 30
['CRMLSSold202401_filled.csv', 'CRMLSSold202402_filled.csv', 'CRMLSSold202403_filled.csv', 'CRMLSSold202404_filled.csv', 'CRMLSSold202405_filled.csv', 'CRMLSSold202406_filled.csv', 'CRMLSSold202407_filled.csv', 'CRMLSSold202408.csv', 'CRMLSSold202409.csv', 'CRMLSSold202410.csv', 'CRMLSSold202411.csv', 'CRMLSSold202412.csv', 'CRMLSSold202501_filled.csv', 'CRMLSSold202502.csv', 'CRMLSSold202503.csv', 'CRMLSSold202504.csv', 'CRMLSSold202505.csv', 'CRMLSSold202506.csv', 'CRMLSSold202507.csv', 'CRMLSSold202508.csv', 'CRMLSSold202509.csv', 'CRMLSSold202510.csv', 'CRMLSSold202511.csv', 'CRMLSSold202512.csv', 'CRMLSSold202601.csv', 'CRMLSSold202602.csv', 'CRMLSSold202603.csv', 'CRMLSSold202604.csv', 'CRMLSSold202605.csv', 'CRMLSSold202606.csv']
Raw shape: (660950, 83)

## 2. Filter Project Scope and Target

- The project scope:  `Residential` + `SingleFamilyResidence`.
- The target is `ClosePrice`, so rows without a valid positive close price are dropped.

In [3]:
df = raw_df.copy()

# Parse target and date fields.
df["ClosePrice"] = pd.to_numeric(df["ClosePrice"], errors="coerce")

transaction_date_cols = [
    "CloseDate",
    "ListingContractDate",
    "PurchaseContractDate",
    "ContractStatusChangeDate",
]
for col in transaction_date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

if "DaysOnMarket" in df.columns:
    df["DaysOnMarket"] = pd.to_numeric(df["DaysOnMarket"], errors="coerce")

df["close_month"] = df["CloseDate"].dt.to_period("M")

# Target/date validity.
df = df[df["CloseDate"].notna()]
df = df[df["ClosePrice"].notna()]
df = df[df["ClosePrice"] > 0]

# Task-specific property filter.
df = df[
    (df["PropertyType"] == "Residential") &
    (df["PropertySubType"].astype(str).str.replace(" ", "", regex=False) == "SingleFamilyResidence")
].copy()

df.shape

(333361, 84)

## 3. Deduplicate Listings

By EDA, we found duplicated `ListingKey` values.

In [4]:
rows_before = len(df)

df = df.sort_values(["ListingKey", "CloseDate", "source_file"])
df = df.drop_duplicates(subset=["ListingKey"], keep="last")

print(f"Duplicate ListingKey rows removed: {rows_before - len(df):,}")
print(df.shape)

Duplicate ListingKey rows removed: 285
(333076, 84)

## 4. Define Feature Decisions

In [5]:
target = "ClosePrice"
id_col = "ListingKey"
metadata_cols = [id_col, "CloseDate", "close_month", "source_file"]

continuous_numeric_cols = [
    "LivingArea",
    "LotSizeSquareFeet",
    "YearBuilt",
    "Latitude",
    "Longitude",
    "AssociationFee"
]

# Count / ordinal numeric predictors.
# These are numeric, but they are discrete counts rather than continuous measurements.
count_numeric_cols = [
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "GarageSpaces",
    "ParkingTotal",
    "Stories"
]

# Combined numeric list used for model features and missing flags.
numeric_cols = continuous_numeric_cols + count_numeric_cols

boolean_cols = [
    "ViewYN",
    "PoolPrivateYN",
    "AttachedGarageYN",
    "FireplaceYN",
    "NewConstructionYN",
]

categorical_cols = [
    "City",
    "CountyOrParish",
    "PostalCode",  # standardized to 5-digit ZIP during cleaning
    "MLSAreaMajor",
    "Levels",
    "HighSchoolDistrict",
]

# Extra fields used for preprocessing quality checks. These are kept for auditability,
# but they are not part of numeric_cols/categorical_cols unless explicitly listed above.
quality_check_cols = [
    "LotSizeAcres",
    "ListingContractDate",
    "PurchaseContractDate",
    "ContractStatusChangeDate",
    "DaysOnMarket",
    "Flooring",
]

# Keep only columns that exist in the current raw files.
metadata_cols = [col for col in metadata_cols if col in df.columns]
numeric_cols = [col for col in numeric_cols if col in df.columns]
boolean_cols = [col for col in boolean_cols if col in df.columns]
categorical_cols = [col for col in categorical_cols if col in df.columns]
quality_check_cols = [col for col in quality_check_cols if col in df.columns]

selected_cols = list(dict.fromkeys(metadata_cols + [target] + numeric_cols + categorical_cols + boolean_cols + quality_check_cols))
clean_df = df[selected_cols].copy()

print(f"Clean base shape: {clean_df.shape}")
print(f"Quality check columns: {quality_check_cols}")

Clean base shape: (333076, 33)
Quality check columns: ['LotSizeAcres', 'ListingContractDate', 'PurchaseContractDate', 'ContractStatusChangeDate', 'DaysOnMarket', 'Flooring']

### 4.1 Levels and Stories Consistency Check

Before changing `Levels`, compare the standard single-value categories (`One`, `Two`, `ThreeOrMore`, `MultiSplit`) against numeric `Stories`. Rows with multiple `Levels` values are kept separate so their cleanup rule can be chosen from evidence rather than folded into the main categories prematurely.

In [6]:
raw_df["Levels"].value_counts(dropna=False)

Levels
One                               332773
Two                               192375
NaN                                89568
ThreeOrMore                        27968
MultiSplit                         13127
One,Two                             1765
Two,MultiSplit                      1207
ThreeOrMore,MultiSplit               806
One,MultiSplit                       402
Two,One                              329
Two,ThreeOrMore                      304
One,ThreeOrMore                      145
One,Two,MultiSplit                    49
One,Two,ThreeOrMore                   47
MultiSplit,One                        33
Two,ThreeOrMore,MultiSplit            32
ThreeOrMore,One                        8
One,Two,ThreeOrMore,MultiSplit         5
One,ThreeOrMore,MultiSplit             4
Two,MultiSplit,One                     3
Name: count, dtype: int64

In [7]:
if {"Levels", "Stories"}.issubset(clean_df.columns):
    levels_raw = clean_df["Levels"].astype("string").str.strip().str.replace(r"\s+", " ", regex=True)
    stories_numeric = pd.to_numeric(clean_df["Stories"], errors="coerce")
    levels_story_check = pd.DataFrame({
        "Levels": levels_raw.fillna("__missing__"),
        "Stories": stories_numeric,
    })

    single_level_values = ["One", "Two", "ThreeOrMore", "MultiSplit"]
    known_level_values = single_level_values + ["__missing__"]
    single_level_mask = levels_story_check["Levels"].isin(single_level_values)
    multi_or_other_mask = ~levels_story_check["Levels"].isin(known_level_values)

    levels_story_counts = pd.crosstab(
        levels_story_check.loc[single_level_mask, "Levels"],
        levels_story_check.loc[single_level_mask, "Stories"],
        dropna=False,
    )

    levels_story_summary = (
        levels_story_check.loc[single_level_mask]
        .groupby("Levels")["Stories"]
        .agg(
            rows="size",
            non_missing="count",
            missing=lambda s: s.isna().sum(),
            mean="mean",
            median="median",
            min="min",
            max="max",
        )
        .sort_index()
    )

    expected_story_checks = {
        "One": lambda s: s.eq(1),
        "Two": lambda s: s.eq(2),
        "ThreeOrMore": lambda s: s.ge(3),
        "MultiSplit": lambda s: s.notna(),
    }
    expected_story_rows = []
    for level_value, expected_check in expected_story_checks.items():
        level_stories = levels_story_check.loc[levels_story_check["Levels"].eq(level_value), "Stories"]
        non_missing = level_stories.notna()
        expected_story_rows.append({
            "Levels": level_value,
            "rows": len(level_stories),
            "non_missing_stories": int(non_missing.sum()),
            "expected_story_share": expected_check(level_stories).sum() / non_missing.sum() if non_missing.any() else np.nan,
        })
    expected_story_summary = pd.DataFrame(expected_story_rows)

    ordinal_level_map = {"One": 1, "Two": 2, "ThreeOrMore": 3}
    ordinal_check = levels_story_check.loc[
        levels_story_check["Levels"].isin(ordinal_level_map) & levels_story_check["Stories"].notna()
    ].copy()
    ordinal_check["LevelsOrdinal"] = ordinal_check["Levels"].map(ordinal_level_map)
    levels_stories_spearman = ordinal_check[["LevelsOrdinal", "Stories"]].corr(method="spearman").loc["LevelsOrdinal", "Stories"]
    levels_story_association = pd.DataFrame([{
        "metric": "spearman_corr_single_ordinal_levels_vs_stories",
        "rows_used": len(ordinal_check),
        "value": levels_stories_spearman,
    }])

    multi_level_story_summary = (
        levels_story_check.loc[multi_or_other_mask]
        .groupby("Levels")["Stories"]
        .agg(
            rows="size",
            non_missing="count",
            missing=lambda s: s.isna().sum(),
            mean="mean",
            median="median",
            min="min",
            max="max",
        )
        .sort_values("rows", ascending=False)
    )

    print(f"Single known Levels rows: {single_level_mask.sum():,}")
    print(f"Multi/other Levels rows: {multi_or_other_mask.sum():,} ({multi_or_other_mask.mean():.2%})")
    display(levels_story_counts)
    display(levels_story_summary)
    display(expected_story_summary)
    display(levels_story_association)
    display(multi_level_story_summary.head(30))
else:
    print("Levels and/or Stories are not present in the selected columns.")

Single known Levels rows: 299,794
Multi/other Levels rows: 2,081 (0.62%)

Stories         1.0     2.0   NaN
Levels
MultiSplit       23       0  4678
One          186611       0     0
ThreeOrMore       6       0  6316
Two             313  101847     0

               rows  non_missing  missing      mean  median  min  max
Levels
MultiSplit     4701           23     4678  1.000000     1.0  1.0  1.0
One          186611       186611        0  1.000000     1.0  1.0  1.0
ThreeOrMore    6322            6     6316  1.000000     1.0  1.0  1.0
Two          102160       102160        0  1.996936     2.0  1.0  2.0

        Levels    rows  non_missing_stories  expected_story_share
0          One  186611               186611              1.000000
1          Two  102160               102160              0.996936
2  ThreeOrMore    6322                    6              0.000000
3   MultiSplit    4701                   23              1.000000

                                           metric  rows_used     value
0  spearman_corr_single_ordinal_levels_vs_stories     288777  0.997548

,rows,non_missing,missing,mean,median,min,max
Levels,,,,,,,
"One,Two",685,685,0,1.000000,1.0,1.0,1.0
"Two,MultiSplit",492,492,0,1.997967,2.0,1.0,2.0
"Two,One",264,264,0,1.000000,1.0,1.0,1.0
"ThreeOrMore,MultiSplit",229,0,229,NaN,NaN,NaN,NaN
"One,MultiSplit",182,182,0,1.000000,1.0,1.0,1.0
"Two,ThreeOrMore",116,116,0,2.000000,2.0,2.0,2.0
"One,ThreeOrMore",49,49,0,1.000000,1.0,1.0,1.0
"MultiSplit,One",26,26,0,1.000000,1.0,1.0,1.0
"One,Two,MultiSplit",13,13,0,1.000000,1.0,1.0,1.0
"Two,ThreeOrMore,MultiSplit",8,8,0,2.000000,2.0,2.0,2.0
"One,Two,ThreeOrMore",6,6,0,1.000000,1.0,1.0,1.0
"ThreeOrMore,One",6,6,0,1.000000,1.0,1.0,1.0
"One,Two,ThreeOrMore,MultiSplit",3,3,0,1.000000,1.0,1.0,1.0
"Two,MultiSplit,One",2,2,0,1.000000,1.0,1.0,1.0

## 5. Clean Numeric, Boolean, Location, ZIP, Lot Size, and Date Quality Values

This section applies row-level preprocessing decisions based on the added EDA checks:

- convert numeric columns to numeric dtype
- remove clearly non-California records
- flag invalid coordinates and set bad coordinates to missing
- compare `LotSizeAcres` with `LotSizeSquareFeet` using 43,560 square feet per acre
- add numeric sanity flags for unusually large homes, large lots, and price-per-square-foot diagnostics
- standardize `PostalCode` to the first 5-digit ZIP for modeling
- run date-order sanity checks and keep issue flags
- convert impossible numeric values to missing
- convert boolean fields to 0/1 before creating missing flags
- add missing-value flags after boolean normalization
- clean categorical text values

In [8]:
raw_df["Flooring"].value_counts(dropna=False)

Flooring
NaN                                    272114
Wood                                    43832
Laminate                                42355
Carpet,Tile                             38040
Tile,Wood                               30439
                                        ...
Brick,Stone,Tile,Vinyl                      1
Brick,Carpet,Laminate,Tile,Wood             1
Bamboo,Laminate,Tile,Vinyl,Wood             1
Brick,SeeRemarks,Tile,Wood                  1
Bamboo,Carpet,SeeRemarks,Vinyl,Wood         1
Name: count, Length: 356, dtype: int64

In [9]:
clean_df = clean_df.copy()

# 1. Numeric cleaning: convert invalid strings to NaN.
for col in numeric_cols + ["LotSizeAcres", "DaysOnMarket"]:
    if col in clean_df.columns:
        clean_df[col] = pd.to_numeric(clean_df[col], errors="coerce")

# 2. Drop records that are explicitly outside the California modeling scope.
# These are not just bad coordinates; the location labels themselves are non-CA.
if "CountyOrParish" in clean_df.columns:
    non_ca_location = clean_df["CountyOrParish"].isin(["Foreign Country", "Other State"])
    print(f"Dropping non-California location rows: {non_ca_location.sum():,}")
    clean_df = clean_df.loc[~non_ca_location].copy()

# 3. Coordinate quality flag.
ca_lat_min, ca_lat_max = 32.0, 42.5
ca_lon_min, ca_lon_max = -125.0, -113.0

if {"Latitude", "Longitude"}.issubset(clean_df.columns):
    coords_present = clean_df["Latitude"].notna() & clean_df["Longitude"].notna()
    invalid_coords = coords_present & (
        ~clean_df["Latitude"].between(ca_lat_min, ca_lat_max)
        | ~clean_df["Longitude"].between(ca_lon_min, ca_lon_max)
    )

    clean_df["invalid_coordinates_flag"] = invalid_coords.astype(int)
    clean_df.loc[invalid_coords, ["Latitude", "Longitude"]] = np.nan
    print(f"Rows with coordinates present: {int(coords_present.sum()):,}")
    print(f"Invalid coordinate rows flagged: {int(invalid_coords.sum()):,}")
else:
    clean_df["invalid_coordinates_flag"] = 0

# 4. Convert impossible numeric values to missing.
if "LivingArea" in clean_df.columns:
    clean_df.loc[clean_df["LivingArea"] <= 0, "LivingArea"] = np.nan
if "BedroomsTotal" in clean_df.columns:
    clean_df.loc[clean_df["BedroomsTotal"] < 0, "BedroomsTotal"] = np.nan
if "BathroomsTotalInteger" in clean_df.columns:
    clean_df.loc[clean_df["BathroomsTotalInteger"] < 0, "BathroomsTotalInteger"] = np.nan
if "LotSizeSquareFeet" in clean_df.columns:
    clean_df.loc[clean_df["LotSizeSquareFeet"] <= 0, "LotSizeSquareFeet"] = np.nan
if "LotSizeAcres" in clean_df.columns:
    clean_df.loc[clean_df["LotSizeAcres"] <= 0, "LotSizeAcres"] = np.nan
if "YearBuilt" in clean_df.columns:
    current_year = pd.Timestamp.today().year
    clean_df.loc[~clean_df["YearBuilt"].between(1800, current_year + 1), "YearBuilt"] = np.nan
for col in ["GarageSpaces", "ParkingTotal", "Stories", "AssociationFee"]:
    if col in clean_df.columns:
        clean_df.loc[clean_df[col] < 0, col] = np.nan

# 5. Lot size unit consistency check.
# If acres and square feet disagree materially, flag the row and set LotSizeSquareFeet to missing.
# If square feet is missing but acres is valid, derive square feet from acres and flag that derivation.
clean_df["lot_size_unit_mismatch_flag"] = 0
clean_df["lot_size_sqft_derived_from_acres_flag"] = 0

if {"LotSizeAcres", "LotSizeSquareFeet"}.issubset(clean_df.columns):
    acres = clean_df["LotSizeAcres"]
    sqft = clean_df["LotSizeSquareFeet"]
    expected_sqft = acres * 43560

    both_available = acres.notna() & sqft.notna()
    abs_sqft_diff = (sqft - expected_sqft).abs()
    abs_pct_diff = abs_sqft_diff / expected_sqft
    lot_size_mismatch = both_available & (abs_sqft_diff > 50) & (abs_pct_diff > 0.02)

    clean_df.loc[lot_size_mismatch, "lot_size_unit_mismatch_flag"] = 1
    clean_df.loc[lot_size_mismatch, "LotSizeSquareFeet"] = np.nan

    missing_sqft_with_acres = clean_df["LotSizeSquareFeet"].isna() & clean_df["LotSizeAcres"].notna() & ~lot_size_mismatch
    clean_df.loc[missing_sqft_with_acres, "LotSizeSquareFeet"] = clean_df.loc[missing_sqft_with_acres, "LotSizeAcres"] * 43560
    clean_df.loc[missing_sqft_with_acres, "lot_size_sqft_derived_from_acres_flag"] = 1

    print(f"Lot size unit mismatch rows flagged: {int(lot_size_mismatch.sum()):,}")
    print(f"LotSizeSquareFeet rows derived from acres: {int(missing_sqft_with_acres.sum()):,}")

# 5b. Numeric sanity flags for large homes, large lots, and target-based price-per-square-foot diagnostics.
# PricePerSqFt uses ClosePrice, so it is kept for cleaning diagnostics only and must not be used as a model feature.
clean_df["large_home_gt_7000_sqft_flag"] = 0
clean_df["large_lot_gt_10_acres_flag"] = 0
clean_df["extreme_lot_gt_100_acres_flag"] = 0
clean_df["price_per_sqft_low_flag"] = 0
clean_df["price_per_sqft_high_flag"] = 0

if "LivingArea" in clean_df.columns:
    clean_df["large_home_gt_7000_sqft_flag"] = clean_df["LivingArea"].gt(7000).fillna(False).astype(int)
    clean_df.loc[clean_df["LivingArea"].gt(15000).fillna(False), "LivingArea"] = np.nan

if "LotSizeAcres" in clean_df.columns:
    clean_df["large_lot_gt_10_acres_flag"] = clean_df["LotSizeAcres"].gt(10).fillna(False).astype(int)
    extreme_lot = clean_df["LotSizeAcres"].gt(100).fillna(False)
    clean_df["extreme_lot_gt_100_acres_flag"] = extreme_lot.astype(int)
    clean_df.loc[extreme_lot, "LotSizeAcres"] = np.nan
    if "LotSizeSquareFeet" in clean_df.columns:
        clean_df.loc[extreme_lot, "LotSizeSquareFeet"] = np.nan

if {target, "LivingArea"}.issubset(clean_df.columns):
    clean_df["PricePerSqFt_sanity_check"] = np.where(
        clean_df[target].gt(0) & clean_df["LivingArea"].gt(0),
        clean_df[target] / clean_df["LivingArea"],
        np.nan,
    )
    clean_df["price_per_sqft_low_flag"] = clean_df["PricePerSqFt_sanity_check"].lt(100).fillna(False).astype(int)
    clean_df["price_per_sqft_high_flag"] = clean_df["PricePerSqFt_sanity_check"].gt(2000).fillna(False).astype(int)
else:
    clean_df["PricePerSqFt_sanity_check"] = np.nan

numeric_sanity_summary = pd.DataFrame([
    {"check": "LivingArea > 7,000 sqft", "flagged_rows": int(clean_df["large_home_gt_7000_sqft_flag"].sum())},
    {"check": "LotSizeAcres > 10", "flagged_rows": int(clean_df["large_lot_gt_10_acres_flag"].sum())},
    {"check": "LotSizeAcres > 100 set to missing", "flagged_rows": int(clean_df["extreme_lot_gt_100_acres_flag"].sum())},
    {"check": "PricePerSqFt < $100", "flagged_rows": int(clean_df["price_per_sqft_low_flag"].sum())},
    {"check": "PricePerSqFt > $2,000", "flagged_rows": int(clean_df["price_per_sqft_high_flag"].sum())},
])
display(numeric_sanity_summary)

# 6. PostalCode standardization: use only the first 5-digit ZIP for modeling.
if "PostalCode" in clean_df.columns:
    postal_raw = clean_df["PostalCode"].astype("string").str.strip()
    postal_missing = postal_raw.isna() | postal_raw.eq("")
    postal5 = postal_raw.str.extract(r"(\d{5})", expand=False)
    postal_format_issue = (~postal_missing) & postal5.isna()

    clean_df["PostalCode_format_issue_flag"] = postal_format_issue.astype(int)
    clean_df["PostalCode"] = postal5.fillna("__missing__")

    print(f"PostalCode rows without extractable 5-digit ZIP: {int(postal_format_issue.sum()):,}")
else:
    clean_df["PostalCode_format_issue_flag"] = 0

# 7. Date order sanity checks. Keep flags for auditability; do not drop rows here.
for col in ["ListingContractDate", "PurchaseContractDate", "ContractStatusChangeDate"]:
    if col in clean_df.columns:
        clean_df[col] = pd.to_datetime(clean_df[col], errors="coerce")

date_sanity_rows = []
date_issue_flags = []
date_order_checks = [
    ("listing_after_purchase_flag", "ListingContractDate", "PurchaseContractDate", "ListingContractDate <= PurchaseContractDate"),
    ("purchase_after_close_flag", "PurchaseContractDate", "CloseDate", "PurchaseContractDate <= CloseDate"),
    ("listing_after_close_flag", "ListingContractDate", "CloseDate", "ListingContractDate <= CloseDate"),
]

for flag_col, start_col, end_col, check_name in date_order_checks:
    clean_df[flag_col] = 0
    if start_col in clean_df.columns and end_col in clean_df.columns:
        comparable = clean_df[start_col].notna() & clean_df[end_col].notna()
        violations = comparable & (clean_df[start_col] > clean_df[end_col])
        clean_df.loc[violations, flag_col] = 1
        date_issue_flags.append(flag_col)
        date_sanity_rows.append({
            "check": check_name,
            "n_compared": int(comparable.sum()),
            "n_violations": int(violations.sum()),
            "violation_rate": float(violations.sum() / comparable.sum()) if comparable.sum() else np.nan,
        })

if "DaysOnMarket" in clean_df.columns:
    clean_df["negative_days_on_market_flag"] = clean_df["DaysOnMarket"].lt(0).fillna(False).astype(int)
    date_issue_flags.append("negative_days_on_market_flag")
    comparable = clean_df["DaysOnMarket"].notna()
    violations = comparable & (clean_df["DaysOnMarket"] < 0)
    date_sanity_rows.append({
        "check": "DaysOnMarket >= 0",
        "n_compared": int(comparable.sum()),
        "n_violations": int(violations.sum()),
        "violation_rate": float(violations.sum() / comparable.sum()) if comparable.sum() else np.nan,
    })
else:
    clean_df["negative_days_on_market_flag"] = 0
    date_issue_flags.append("negative_days_on_market_flag")

clean_df["date_order_issue_flag"] = clean_df[date_issue_flags].max(axis=1) if date_issue_flags else 0

date_sanity_summary = pd.DataFrame(date_sanity_rows)
display(date_sanity_summary)

# 8. Boolean cleaning. Normalize first so missing flags capture both original missing
# values and unexpected strings that become NaN during normalization.
def normalize_bool(value):
    if pd.isna(value):
        return np.nan
    text = str(value).strip().lower()
    if text in {"true", "t", "yes", "y", "1"}:
        return 1.0
    if text in {"false", "f", "no", "n", "0"}:
        return 0.0
    return np.nan

for col in boolean_cols:
    clean_df[col] = clean_df[col].map(normalize_bool)

# 9. Missing flags after all row-level corrections and boolean normalization.
missing_flag_cols = []
for col in numeric_cols + boolean_cols:
    flag_col = f"{col}_missing"
    clean_df[flag_col] = clean_df[col].isna().astype(int)
    missing_flag_cols.append(flag_col)

# 10. Categorical text cleaning.
for col in categorical_cols:
    clean_df[col] = (
        clean_df[col]
        .astype("string")
        .str.strip()
        .replace("", "__missing__")
        .fillna("__missing__")
    )

# 10.1 Location categorical text normalization.
# Keep full category granularity; only normalize whitespace and missing markers here.
location_text_cols = ["City", "CountyOrParish", "MLSAreaMajor"]
for col in location_text_cols:
    if col in clean_df.columns:
        clean_df[col] = (
            clean_df[col]
            .astype("string")
            .str.strip()
            .str.replace(r"\s+", " ", regex=True)
            .replace("", "__missing__")
            .fillna("__missing__")
        )

# 11. Levels canonicalization.
# Multi-value entries are resolved with Stories when it provides a clear floor count.
if {"Levels", "Stories"}.issubset(clean_df.columns):
    final_levels = ["One", "Two", "ThreeOrMore", "MultiSplit", "MultipleReported", "__missing__"]
    stories_numeric = pd.to_numeric(clean_df["Stories"], errors="coerce")
    multi_value_levels = ~clean_df["Levels"].isin(final_levels)

    clean_df.loc[multi_value_levels & stories_numeric.eq(1), "Levels"] = "One"
    clean_df.loc[multi_value_levels & stories_numeric.eq(2), "Levels"] = "Two"

    unresolved_multi_value_levels = ~clean_df["Levels"].isin(final_levels)
    clean_df.loc[unresolved_multi_value_levels, "Levels"] = "MultipleReported"

    assert set(clean_df["Levels"].unique()).issubset(final_levels)
    display(clean_df["Levels"].value_counts(dropna=False).reindex(final_levels, fill_value=0).to_frame("rows"))

# 12. Flooring multi-label cleaning.
# The raw Flooring field is comma-separated; use material flags instead of sparse raw combinations.
if "Flooring" in clean_df.columns:
    flooring_raw = (
        clean_df["Flooring"]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .replace("", "__missing__")
        .fillna("__missing__")
    )

    flooring_materials = ["Carpet", "Tile", "Wood", "Laminate", "Vinyl", "Stone", "Concrete", "Bamboo", "Brick"]
    flooring_indicator_cols = [f"Flooring_{material}" for material in flooring_materials] + ["Flooring_SeeRemarks"]

    flooring_token_sets = flooring_raw.apply(
        lambda value: set() if value == "__missing__" else {token.strip() for token in str(value).split(",") if token.strip()}
    )

    for material in flooring_materials:
        clean_df[f"Flooring_{material}"] = flooring_token_sets.apply(lambda tokens, material=material: int(material in tokens))

    clean_df["Flooring_SeeRemarks"] = flooring_token_sets.apply(lambda tokens: int("SeeRemarks" in tokens))
    clean_df["Flooring_missing"] = flooring_raw.eq("__missing__").astype(int)
    clean_df["Flooring_material_count"] = clean_df[[f"Flooring_{material}" for material in flooring_materials]].sum(axis=1)
    clean_df["Flooring_multiple_materials_flag"] = clean_df["Flooring_material_count"].gt(1).astype(int)

    flooring_expected_tokens = set(flooring_materials + ["SeeRemarks"])
    flooring_unexpected_tokens = sorted(set().union(*flooring_token_sets) - flooring_expected_tokens) if len(flooring_token_sets) else []
    if flooring_unexpected_tokens:
        print(f"Unexpected Flooring tokens: {flooring_unexpected_tokens}")

    numeric_cols = numeric_cols + ["Flooring_material_count"]
    boolean_cols = boolean_cols + flooring_indicator_cols + ["Flooring_multiple_materials_flag"]
    clean_df = clean_df.drop(columns=["Flooring"])

cleaning_summary = pd.DataFrame({
    "column": numeric_cols + boolean_cols + categorical_cols,
    "missing_rate_after_cleaning": clean_df[numeric_cols + boolean_cols + categorical_cols].isna().mean().values,
})

display(cleaning_summary.sort_values("missing_rate_after_cleaning", ascending=False))
print(f"Rows after cleaning: {len(clean_df):,}")

Dropping non-California location rows: 16
Rows with coordinates present: 332,959
Invalid coordinate rows flagged: 75
Lot size unit mismatch rows flagged: 173
LotSizeSquareFeet rows derived from acres: 19

                               check  flagged_rows
0            LivingArea > 7,000 sqft          1470
1                  LotSizeAcres > 10          1933
2  LotSizeAcres > 100 set to missing           300
3                PricePerSqFt < $100           522
4              PricePerSqFt > $2,000          3020

PostalCode rows without extractable 5-digit ZIP: 0

,check,n_compared,n_violations,violation_rate
0,ListingContractDate <= PurchaseContractDate,332922,203,0.000610
1,PurchaseContractDate <= CloseDate,332922,196,0.000589
2,ListingContractDate <= CloseDate,333060,46,0.000138
3,DaysOnMarket >= 0,333060,42,0.000126

                    rows
Levels
One               187839
Two               102770
ThreeOrMore         6321
MultiSplit          4700
MultipleReported     229
__missing__        31201

                              column  missing_rate_after_cleaning
5                     AssociationFee                     0.302348
10                           Stories                     0.126130
14                  AttachedGarageYN                     0.116517
13                     PoolPrivateYN                     0.095526
12                            ViewYN                     0.089654
16                 NewConstructionYN                     0.073083
8                       GarageSpaces                     0.037273
1                  LotSizeSquareFeet                     0.019015
9                       ParkingTotal                     0.001282
0                         LivingArea                     0.001093
2                          YearBuilt                     0.000724
15                       FireplaceYN                     0.000664
4                          Longitude                     0.000528
3                           Latitude                     0.000528
7              BathroomsTotalInteger                     0.000150
31                      MLSAreaMajor                     0.000000
24                   Flooring_Bamboo                     0.000000
32                            Levels                     0.000000
30                        PostalCode                     0.000000
29                    CountyOrParish                     0.000000
28                              City                     0.000000
27  Flooring_multiple_materials_flag                     0.000000
26               Flooring_SeeRemarks                     0.000000
25                    Flooring_Brick                     0.000000
17                   Flooring_Carpet                     0.000000
23                 Flooring_Concrete                     0.000000
22                    Flooring_Stone                     0.000000
21                    Flooring_Vinyl                     0.000000
20                 Flooring_Laminate                     0.000000
19                     Flooring_Wood                     0.000000
18                     Flooring_Tile                     0.000000
11           Flooring_material_count                     0.000000
6                      BedroomsTotal                     0.000000
33                HighSchoolDistrict                     0.000000

Rows after cleaning: 333,060

## 6. Export Cleaned Data

In [10]:
export_df = clean_df.copy()
export_df["log_ClosePrice"] = np.log1p(export_df[target])
export_df.to_csv(CLEANED_CSV, index=False)

print(f"Saved cleaned data: {CLEANED_CSV}")

Saved cleaned data: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/processed/crmls_week3_cleaned.csv

## 7. Time-Based Split Setup

The updated project reporting scope uses `2025-12` through `2026-06`, with `2026-06` as the new final test month. Instead of selecting among multiple `X` windows, keep the final baseline window fixed and use rolling-origin backtests only to check whether performance is stable across historical cutoffs.

Split design:
- fixed training window length: 12 months
- historical stability cutoffs: `2025-09`, `2025-11`, `2026-01`, `2026-03`, `2026-05`
- final test month: `2026-06`, used once at the end

For each cutoff, the model trains on the 12 months immediately before the evaluation month. The official final baseline is trained on `2025-06` through `2026-05` and tested on `2026-06`.

In [11]:
available_months = sorted(clean_df["close_month"].dropna().unique())

scope_start = pd.Period("2025-12", freq="M")
scope_end = pd.Period("2026-06", freq="M")
scope_months = [month for month in available_months if scope_start <= month <= scope_end]

expected_scope_months = [pd.Period(month, freq="M") for month in [
    "2025-12", "2026-01", "2026-02", "2026-03", "2026-04", "2026-05", "2026-06"
]]
if scope_months != expected_scope_months:
    raise ValueError(f"Expected reporting scope {expected_scope_months}, found {scope_months}.")

fixed_train_months = 12
historical_eval_months = [
    pd.Period("2025-09", freq="M"),
    pd.Period("2025-11", freq="M"),
    pd.Period("2026-01", freq="M"),
    pd.Period("2026-03", freq="M"),
    pd.Period("2026-05", freq="M"),
]
test_month = pd.Period("2026-06", freq="M")

print(f"Available months: {available_months[0]} to {available_months[-1]}")
print(f"Reporting scope: {scope_months[0]} to {scope_months[-1]}")
print(f"Historical stability cutoffs: {', '.join(str(month) for month in historical_eval_months)}")
print(f"Final test month: {test_month}")
print(f"Fixed training window length: {fixed_train_months} months")


def get_fixed_train_months(end_month):
    """Return the fixed number of months immediately before end_month."""
    end_idx = available_months.index(end_month)
    start_idx = end_idx - fixed_train_months
    if start_idx < 0:
        raise ValueError(f"Not enough months before {end_month} for {fixed_train_months}-month training window.")
    return available_months[start_idx:end_idx]


def make_rolling_split(data, eval_month):
    """Historical rolling-origin split for the fixed training window."""
    train_months = get_fixed_train_months(eval_month)
    train_df = data[data["close_month"].isin(train_months)].copy()
    eval_df = data[data["close_month"] == eval_month].copy()
    return train_df, eval_df, train_months, eval_month


def make_final_test_split(data):
    """Final split: train on the six months before the fixed final test month."""
    train_months = get_fixed_train_months(test_month)
    train_df = data[data["close_month"].isin(train_months)].copy()
    test_df = data[data["close_month"] == test_month].copy()
    return train_df, test_df, train_months, test_month

Available months: 2024-01 to 2026-06
Reporting scope: 2025-12 to 2026-06
Historical stability cutoffs: 2025-09, 2025-11, 2026-01, 2026-03, 2026-05
Final test month: 2026-06
Fixed training window length: 12 months

## 8. Fixed-Window Rolling-Origin Split Plan

This table prepares the Week 4 stability-check design. The training-window length is fixed; only the historical cutoff changes.

In [12]:
split_plan_rows = []

for eval_month in historical_eval_months:
    rolling_train_df, rolling_eval_df, train_months, eval_month_value = make_rolling_split(
        clean_df,
        eval_month=eval_month,
    )
    split_plan_rows.append({
        "split_type": "historical_eval",
        "train_window_months": fixed_train_months,
        "train_month_start": str(train_months[0]),
        "train_month_end": str(train_months[-1]),
        "train_months": ", ".join(str(month) for month in train_months),
        "eval_month": str(eval_month_value),
        "train_rows": len(rolling_train_df),
        "eval_rows": len(rolling_eval_df),
    })

final_train_df, test_df, final_train_months, test_month_value = make_final_test_split(clean_df)
split_plan_rows.append({
    "split_type": "final_test",
    "train_window_months": fixed_train_months,
    "train_month_start": str(final_train_months[0]),
    "train_month_end": str(final_train_months[-1]),
    "train_months": ", ".join(str(month) for month in final_train_months),
    "eval_month": str(test_month_value),
    "train_rows": len(final_train_df),
    "eval_rows": len(test_df),
})

split_plan = pd.DataFrame(split_plan_rows)
split_plan.to_csv(SPLIT_PLAN_CSV, index=False)

print(f"Saved split plan: {SPLIT_PLAN_CSV}")
display(split_plan)

Saved split plan: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/processed/crmls_week3_split_plan.csv

,split_type,train_window_months,train_month_start,train_month_end,train_months,eval_month,train_rows,eval_rows
0,historical_eval,12,2024-09,2025-08,"2024-09, 2024-10, 2024-11, 2024-12, 2025-01, 2...",2025-09,130976,11449
1,historical_eval,12,2024-11,2025-10,"2024-11, 2024-12, 2025-01, 2025-02, 2025-03, 2...",2025-11,131211,9720
2,historical_eval,12,2025-01,2025-12,"2025-01, 2025-02, 2025-03, 2025-04, 2025-05, 2...",2026-01,130093,7485
3,historical_eval,12,2025-03,2026-02,"2025-03, 2025-04, 2025-05, 2025-06, 2025-07, 2...",2026-03,129139,11169
4,historical_eval,12,2025-05,2026-04,"2025-05, 2025-06, 2025-07, 2025-08, 2025-09, 2...",2026-05,129862,12014
5,final_test,12,2025-06,2026-05,"2025-06, 2025-07, 2025-08, 2025-09, 2025-10, 2...",2026-06,130114,12858

## 9. Save Cleaned Split Files

Save one file per fixed-window rolling-origin train/evaluation split. Outlier thresholds are intentionally not applied here because they must be learned from each fold's training data inside the modeling notebook.

In [13]:
SPLIT_DIR = PROCESSED_DATA_DIR / "splits"
SPLIT_DIR.mkdir(parents=True, exist_ok=True)

# Clear prior generated split CSVs so stale files from older experiments do not confuse the Week 4 run.
for old_split_path in SPLIT_DIR.glob("*.csv"):
    old_split_path.unlink()

for eval_month in historical_eval_months:
    rolling_train_df, rolling_eval_df, _, _ = make_rolling_split(clean_df, eval_month=eval_month)

    train_path = SPLIT_DIR / f"rolling_train_eval_{eval_month}_cleaned.csv"
    eval_path = SPLIT_DIR / f"rolling_eval_{eval_month}_cleaned.csv"

    rolling_train_df.to_csv(train_path, index=False)
    rolling_eval_df.to_csv(eval_path, index=False)
    print(f"Saved historical train/eval split for {eval_month}")

final_train_df, test_df_common, _, _ = make_final_test_split(clean_df)
final_train_path = SPLIT_DIR / "final_train_fixed_window_cleaned.csv"
test_path = SPLIT_DIR / "test_latest_month_cleaned.csv"

final_train_df.to_csv(final_train_path, index=False)
test_df_common.to_csv(test_path, index=False)

print(f"Saved final train set: {final_train_path} ({len(final_train_df):,} rows)")
print(f"Saved final test set: {test_path} ({len(test_df_common):,} rows)")
print(f"Saved fixed-window rolling-origin split files to: {SPLIT_DIR}")

Saved historical train/eval split for 2025-09
Saved historical train/eval split for 2025-11
Saved historical train/eval split for 2026-01
Saved historical train/eval split for 2026-03
Saved historical train/eval split for 2026-05
Saved final train set: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/processed/splits/final_train_fixed_window_cleaned.csv (130,114 rows)
Saved final test set: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/processed/splits/test_latest_month_cleaned.csv (12,858 rows)
Saved fixed-window rolling-origin split files to: /Users/soyeonpark/Projects/IDX_internship_2026/idx-california-price-prediction/data/processed/splits

## 10. Preprocessing Summary

In [14]:
summary = {
    "raw_rows": len(raw_df),
    "cleaned_rows": len(clean_df),
    "available_month_start": str(available_months[0]),
    "available_month_end": str(available_months[-1]),
    "reporting_scope_start": str(scope_months[0]),
    "reporting_scope_end": str(scope_months[-1]),
    "fixed_train_window_months": fixed_train_months,
    "historical_eval_months_for_stability_check": ", ".join(str(month) for month in historical_eval_months),
    "final_test_month": str(test_month),
    "cleaned_columns": export_df.shape[1],
    "cleaned_csv": str(CLEANED_CSV.relative_to(PROJECT_ROOT)),
    "split_plan_csv": str(SPLIT_PLAN_CSV.relative_to(PROJECT_ROOT)),
    "split_dir": str(SPLIT_DIR.relative_to(PROJECT_ROOT)),
}

summary_df = pd.DataFrame([summary]).T.rename(columns={0: "value"})
display(summary_df)

preprocessing_policy = pd.DataFrame([
    {"field_group": "Target", "decision": "Dropped rows where ClosePrice is missing or <= 0. Fold-specific outlier thresholds are learned in modeling."},
    {"field_group": "Project scope", "decision": "Kept Residential / SingleFamilyResidence records only."},
    {"field_group": "Duplicate ListingKey", "decision": "Kept one row per ListingKey after sorting by CloseDate/source_file."},
    {"field_group": "Non-CA rows", "decision": "Dropped rows labeled Foreign Country or Other State."},
    {"field_group": "Coordinates", "decision": "Flagged out-of-range coordinates only when both Latitude and Longitude are present; original coordinate missingness is tracked separately by missing flags."},
    {"field_group": "Lot size consistency", "decision": "Compared LotSizeAcres with LotSizeSquareFeet using 43,560 sqft per acre; flagged large mismatches and set suspect square-foot values to missing."},
    {"field_group": "Numeric sanity flags", "decision": "Flagged large homes, large lots, and target-based PricePerSqFt outliers for diagnostics; set LotSizeAcres > 100 and matching square-foot lot size to missing before modeling."},
    {"field_group": "PostalCode", "decision": "Standardized PostalCode to the first extractable 5-digit ZIP for modeling and flagged unparseable values."},
    {"field_group": "Date sanity", "decision": "Checked listing, purchase-contract, close-date order and negative DaysOnMarket; kept issue flags for auditability."},
    {"field_group": "Numeric predictors", "decision": "Converted impossible values to missing and added missing flags; imputation is deferred."},
    {"field_group": "Boolean predictors", "decision": "Converted values to 0/1 before missing flags are created; remaining missing values will be imputed inside the train-only pipeline."},
    {"field_group": "Categorical predictors", "decision": "Cleaned text values and marked missing/empty strings as __missing__; one-hot encoding is deferred."},
    {"field_group": "Fixed-window stability check", "decision": "Use one fixed 12-month training window and evaluate it over five historical cutoffs."},
    {"field_group": "Final test split", "decision": "Train on the selected 12-month window and reserve 2026-06 as final test."},
    {"field_group": "Leakage control", "decision": "PricePerSqFt_sanity_check uses ClosePrice and is kept for cleaning diagnostics only; it is not included in model feature sets. Modeling notebooks learn price and price-per-square-foot filters inside each train fold."},
])

display(preprocessing_policy)

                                                                                  value
raw_rows                                                                         660950
cleaned_rows                                                                     333060
available_month_start                                                           2024-01
available_month_end                                                             2026-06
reporting_scope_start                                                           2025-12
reporting_scope_end                                                             2026-06
fixed_train_window_months                                                            12
historical_eval_months_for_stability_check  2025-09, 2025-11, 2026-01, 2026-03, 2026-05
final_test_month                                                                2026-06
cleaned_columns                                                                      77
cleaned_csv                                      data/processed/crmls_week3_cleaned.csv
split_plan_csv                                data/processed/crmls_week3_split_plan.csv
split_dir                                                         data/processed/splits

,field_group,decision
0,Target,Dropped rows where ClosePrice is missing or <=...
1,Project scope,Kept Residential / SingleFamilyResidence recor...
2,Duplicate ListingKey,Kept one row per ListingKey after sorting by C...
3,Non-CA rows,Dropped rows labeled Foreign Country or Other ...
4,Coordinates,Flagged out-of-range coordinates only when bot...
5,Lot size consistency,Compared LotSizeAcres with LotSizeSquareFeet u...
6,Numeric sanity flags,"Flagged large homes, large lots, and target-ba..."
7,PostalCode,Standardized PostalCode to the first extractab...
8,Date sanity,"Checked listing, purchase-contract, close-date..."
9,Numeric predictors,Converted impossible values to missing and add...
10,Boolean predictors,Converted values to 0/1 before missing flags a...
11,Categorical predictors,Cleaned text values and marked missing/empty s...
12,Fixed-window stability check,Use one fixed 12-month training window and eva...
13,Final test split,Train on the selected 12-month window and rese...
14,Leakage control,PricePerSqFt_sanity_check uses ClosePrice and ...

## Final Notes

This notebook produces the Week 3 preprocessing deliverables used by Week 4 modeling:
- cleaned base CSV
- fixed-window rolling-origin split plan
- five historical evaluation split files
- final train/test split files

The modeling notebook must fit preprocessing, price outlier thresholds, price-per-square-foot sanity thresholds, and the model separately inside each rolling-origin cutoff.